# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8.1
xcode_project: vinted-ab-ios.xcodeproj
xcode_scheme: vinted-ab-ios
xcode_sdk: iphonesimulator10.2
before_install: 
  - carthage bootstrap --platform iOS --verbose
script:
  - xcodebuild clean build test -project vinted-ab-ios.xcodeproj -scheme vinted-ab-ios -destination 'platform=iOS Simulator,OS=10.1,name=iPhone 7'